version: '3.8'

services:
  cli:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: my_secret_password
      POSTGRES_USER: my_user
      POSTGRES_DB: quake_logs

  rspec:
    build: .
    command: bundle exec rspec --format documentation
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres-data:
