version: '3.8'

services:
  cli:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      APP_ENV: production

  db:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./bin/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_PASSWORD: my_secret_password
      POSTGRES_USER: my_user
      POSTGRES_MULTIPLE_DATABASES: "quake_logs,quake_logs_test"

  rspec:
    build: .
    command: bash -c "ruby spec/support/prepare_test_environment.rb && bundle exec rspec --format documentation"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      APP_ENV: test

volumes:
  postgres-data:
